image: golang:1.10.2-alpine3.7
buildTool: go
env: 
  - "BUILD_DIR=/go/src/bitbucket.org/level11consulting/"
branches:
  - ALL
stages:
  - name: make stoopid dep thing
    script:
      - mkdir -p $BUILD_DIR
      - cp -r . $BUILD_DIR
  - name: install dep & ensure dependencies
    script:
      - cd $BUILD_DIR
      - go get -u github.com/golang/dep/...
      - dep ensure -v
  - name: tag & push
    script:
      - cd $BUILD_DIR
      - go test ./...

